import type { HistoryAnalysis, UsageBucket } from "./analyze.js";
import type { HistorySpendEstimates } from "./cost-estimate.js";
import { formatUkDateTime, type HistoryReportView } from "./report-view.js";

const METRIC_LABELS: Record<string, string> = {
  inputTokens: "Input tokens",
  cachedInputTokens: "Cached input tokens",
  cacheWriteTokens: "Cache write tokens",
  outputTokens: "Output tokens",
  totalTokens: "Total tokens",
  totalNanoAiu: "AI credits (nano-AIU)",
  premiumRequests: "Premium requests",
  durationMs: "API duration (ms)",
};

function esc(value: string | number | undefined | null): string {
  if (value === undefined || value === null || value === "") return "—";
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function table(headers: string[], rows: string[][]): string {
  if (rows.length === 0) {
    return `<p class="empty">(none)</p>`;
  }
  const thead = `<tr>${headers.map((h) => `<th>${esc(h)}</th>`).join("")}</tr>`;
  const tbody = rows
    .map((row) => `<tr>${row.map((c) => `<td>${esc(c)}</td>`).join("")}</tr>`)
    .join("\n");
  return `<div class="table-wrap"><table>\n<thead>${thead}</thead>\n<tbody>\n${tbody}\n</tbody>\n</table></div>`;
}

function usageRows(bucket: UsageBucket): string[][] {
  return Object.entries(bucket.totals)
    .filter(([, value]) => value !== undefined)
    .map(([key, value]) => {
      const sessions = bucket.metricSessions[key as keyof typeof bucket.metricSessions] ?? 0;
      return [METRIC_LABELS[key] ?? key, String(value), String(sessions)];
    });
}

function compactApiUsageRows(
  totals: UsageBucket["totals"],
  estimates: import("./cost-estimate.js").HistorySpendEstimates | undefined,
): string[][] {
  const rows: string[][] = [];
  const nano = totals.totalNanoAiu;
  const aiCredits =
    estimates?.aiCredits ??
    (typeof nano === "number" ? Number((nano / 1_000_000_000).toFixed(9)) : undefined);
  if (aiCredits !== undefined) rows.push(["AI credits", String(aiCredits)]);
  if (nano !== undefined) rows.push(["AI credits (nano-AIU)", String(nano)]);
  for (const key of [
    "totalTokens",
    "inputTokens",
    "outputTokens",
    "cachedInputTokens",
    "cacheWriteTokens",
    "premiumRequests",
    "durationMs",
  ] as const) {
    if (totals[key] !== undefined) {
      rows.push([METRIC_LABELS[key] ?? key, String(totals[key])]);
    }
  }
  return rows;
}

function shell(title: string, view: HistoryReportView, body: string, generatedAt: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${esc(title)}</title>
<style>
  :root {
    color-scheme: light dark;
    --bg: #0f1419; --panel: #1a2332; --text: #e7ecf3; --muted: #9aa8bc;
    --border: #2c3a4f; --accent: #5b9fd4; --row: #152031;
  }
  @media (prefers-color-scheme: light) {
    :root {
      --bg: #f6f8fb; --panel: #ffffff; --text: #152033; --muted: #5b6b7c;
      --border: #d7dee8; --accent: #2563eb; --row: #f0f4f9;
    }
  }
  * { box-sizing: border-box; }
  body { margin: 0; font: 15px/1.5 system-ui, sans-serif; background: var(--bg); color: var(--text); }
  header { padding: 1.5rem 1.75rem 1rem; border-bottom: 1px solid var(--border); background: var(--panel); }
  header h1 { margin: 0 0 0.35rem; font-size: 1.45rem; }
  main { max-width: 1100px; margin: 0 auto; padding: 1.25rem 1.5rem 3rem; }
  section { background: var(--panel); border: 1px solid var(--border); border-radius: 12px; padding: 1rem 1.15rem; margin: 1rem 0; }
  h2 { margin: 0 0 0.75rem; font-size: 1.1rem; }
  h3 { margin: 1rem 0 0.5rem; font-size: 0.98rem; color: var(--muted); }
  .table-wrap { overflow-x: auto; }
  table { width: 100%; border-collapse: collapse; font-size: 0.92rem; }
  th, td { text-align: left; padding: 0.5rem 0.65rem; border-bottom: 1px solid var(--border); vertical-align: top; }
  th { color: var(--muted); font-weight: 600; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.03em; }
  tbody tr:nth-child(even) { background: var(--row); }
  .empty, .note, .disclaimer { color: var(--muted); font-size: 0.9rem; }
  .badge { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 999px; border: 1px solid var(--border); color: var(--accent); font-size: 0.8rem; margin-right: 0.35rem; }
  footer { max-width: 1100px; margin: 0 auto; padding: 0 1.5rem 2rem; color: var(--muted); font-size: 0.85rem; }
</style>
</head>
<body>
<header>
  <h1>${esc(title)}</h1>
  <div>
    <span class="badge">${esc(view)}</span>
    <span class="badge">generated ${esc(formatUkDateTime(generatedAt))} UTC</span>
    <span class="badge">session-level-only</span>
  </div>
</header>
<main>
${body}
</main>
<footer>
  Generated by omp history analyze / skill-retro. Dates are UK DD/MM/YYYY HH:mm (UTC).
  Credit-based dollar columns are omitted; public-rate USD only when pricing matched.
</footer>
</body>
</html>`;
}

function byModelSimpleHtml(estimates: HistorySpendEstimates | undefined): string {
  if (!estimates?.byModel.length) {
    return `<section><h2>By model (API usage)</h2><p class="empty">(none)</p></section>`;
  }
  const rows = estimates.byModel.map((row) => [
    row.model,
    row.inputTokens === undefined ? "—" : String(row.inputTokens),
    row.outputTokens === undefined ? "—" : String(row.outputTokens),
    row.cacheReadTokens === undefined ? "—" : String(row.cacheReadTokens),
    row.cacheWriteTokens === undefined ? "—" : String(row.cacheWriteTokens),
    row.aiCredits === undefined ? "—" : String(row.aiCredits),
    row.estimatedUsdFromPublicRates === undefined
      ? "—"
      : String(row.estimatedUsdFromPublicRates),
  ]);
  const hasPublicUsd = estimates.byModel.some(
    (row) => row.estimatedUsdFromPublicRates !== undefined,
  );
  const note = hasPublicUsd
    ? "API usage from session telemetry. USD column uses public model rates when available."
    : "API usage from session telemetry (always). USD is empty until dollar estimates (public pricing) are requested.";
  return `<section><h2>By model (API usage)</h2>
${table(
  [
    "Model",
    "Input tokens",
    "Output tokens",
    "Cached tokens",
    "Cache write",
    "AI credits",
    "USD (public rates)",
  ],
  rows,
)}
<p class="note">${esc(note)}</p>
</section>`;
}

function byModelAdvancedHtml(estimates: HistorySpendEstimates | undefined): string {
  if (!estimates) {
    return `<section><h2>Spend &amp; models</h2><p class="empty">(none)</p></section>`;
  }
  const summary: string[][] = [
    ["Source", estimates.source],
    ["AI credits", estimates.aiCredits === undefined ? "—" : String(estimates.aiCredits)],
  ];
  if (estimates.pricing) {
    summary.push(
      ["Public pricing attempted", estimates.pricing.attempted ? "yes" : "no"],
      ["Pricing URL", estimates.pricing.sourceUrl ?? "—"],
      ["Retrieved at", formatUkDateTime(estimates.pricing.retrievedAt)],
      ["Matched models", estimates.pricing.matchedModels.join(", ") || "—"],
      ["Unresolved models", estimates.pricing.unresolvedModels.join(", ") || "—"],
    );
  }
  const modelRows = estimates.byModel.map((row) => [
    row.model,
    row.totalNanoAiu === undefined ? "—" : String(row.totalNanoAiu),
    row.aiCredits === undefined ? "—" : String(row.aiCredits),
    row.inputTokens === undefined ? "—" : String(row.inputTokens),
    row.outputTokens === undefined ? "—" : String(row.outputTokens),
    row.estimatedUsdFromPublicRates === undefined
      ? "—"
      : String(row.estimatedUsdFromPublicRates),
  ]);
  return `<section><h2>Spend &amp; models</h2>
${table(["Field", "Value"], summary)}
<p class="disclaimer">${esc(estimates.disclaimer)}</p>
${
  modelRows.length
    ? `<h3>By model</h3>${table(
        ["Model", "nano-AIU", "AI credits", "Input tokens", "Output tokens", "USD (public rates)"],
        modelRows,
      )}`
    : ""
}
</section>`;
}

/** Standalone HTML skill-retro report. Default view is simple. No USD (credits). */
export function formatHistoryHtml(
  report: HistoryAnalysis,
  view: HistoryReportView = "simple",
): string {
  const { filters, coverage, skills, sessionUsage, warnings } = report;
  const skillRows = skills.map((row, index) => [
    String(index + 1),
    row.skill,
    String(row.invocations),
    String(row.sessions),
    formatUkDateTime(row.lastInvokedAt),
  ]);
  const associationRows = sessionUsage.singleSkillAssociations.map((row) => [
    row.skill,
    String(row.sessions),
    String(row.sessionsWithTelemetry),
  ]);

  if (view === "simple") {
    const title = `Skill history — simple (${filters.window}, project=${filters.project})`;
    const body = [
      `<section><h2>Snapshot</h2>`,
      table(
        ["Field", "Value"],
        [
          ["Window", filters.window],
          ["Project", filters.project],
          ["Since", formatUkDateTime(filters.since)],
          ["Skill invocations", String(coverage.invocationsCounted)],
          ["Skills used", String(skills.length)],
          ["Sessions with skills", String(coverage.sessionsWithInvocations)],
          [
            "Sessions matched / discovered",
            `${coverage.sessionsMatched} / ${coverage.sessionsDiscovered}`,
          ],
        ],
      ),
      `</section>`,
      `<section><h2>Top skills</h2>`,
      table(["#", "Skill", "Times used", "Sessions", "Last invoked (UK)"], skillRows),
      `</section>`,
      `<section><h2>API usage</h2>`,
      `<p class="note">Session-level totals only (not per-skill). AI credits always included when telemetry exists.</p>`,
      table(
        ["Metric", "Total"],
        (() => {
          const rows = compactApiUsageRows(sessionUsage.totals, sessionUsage.estimates);
          return rows.length ? rows : [["API usage", "—"]];
        })(),
      ),
      `</section>`,
      byModelSimpleHtml(sessionUsage.estimates),
      `<section><h2>Single-skill associations</h2>`,
      table(["Skill", "Sessions", "With telemetry"], associationRows),
      `</section>`,
    ].join("\n");
    return shell(title, view, body, report.generatedAt);
  }

  const shared = sessionUsage.sharedSkillSessions;
  const warningRows = warnings.map((w) => [w.code, String(w.count), w.message]);
  const title = `Skill history — advanced (${filters.window}, project=${filters.project})`;
  const body = [
    `<section><h2>Window &amp; coverage</h2>`,
    table(
      ["Field", "Value"],
      [
        ["Window", filters.window],
        ["Project", filters.project],
        ["Since", formatUkDateTime(filters.since)],
        ["Generated", formatUkDateTime(report.generatedAt)],
        [
          "Sessions matched / discovered",
          `${coverage.sessionsMatched} / ${coverage.sessionsDiscovered}`,
        ],
        ["Sessions with skill invocations", String(coverage.sessionsWithInvocations)],
        ["Invocations counted", String(coverage.invocationsCounted)],
        ["Skill sessions with telemetry", String(coverage.shutdownTelemetrySessions)],
      ],
    ),
    `</section>`,
    `<section><h2>Top skills</h2>`,
    table(["#", "Skill", "Times used", "Sessions", "Last invoked (UK)"], skillRows),
    `</section>`,
    `<section><h2>Session-level usage</h2>`,
    `<p class="note">Attribution: <strong>session-level-only</strong>.</p>`,
    `<p class="note">Skill sessions: <strong>${esc(sessionUsage.sessions)}</strong> (${esc(sessionUsage.sessionsWithTelemetry)} with telemetry)</p>`,
    table(["Metric", "Total", "Metric sessions"], usageRows(sessionUsage)),
    `</section>`,
    byModelAdvancedHtml(sessionUsage.estimates),
    `<section><h2>Single-skill associations</h2>`,
    table(["Skill", "Sessions", "With telemetry"], associationRows),
    `</section>`,
    `<section><h2>Shared skill sessions</h2>`,
    `<p class="note">Shared sessions: <strong>${esc(shared.sessions)}</strong> (${esc(shared.sessionsWithTelemetry)} with telemetry)</p>`,
    table(["Metric", "Total", "Metric sessions"], usageRows(shared)),
    `</section>`,
    `<section><h2>Warnings</h2>`,
    table(["Code", "Count", "Message"], warningRows),
    `</section>`,
  ].join("\n");
  return shell(title, view, body, report.generatedAt);
}
